name: "DotNet Bump Versions"
description: "A GitHub Action to easily bump .NET Core project version files(.csproj)."
author: "Siqi Lu"
branding:
    icon: "git-commit"
    color: "purple"
inputs:
    version_files:
        description: 'Version files to bump version. You can use Glob pattern string (like "**/*.csproj") or Glob patterns array json string (like "["**/*.csproj", ".version", "**/*.version.json"]"). Patterns supported by Globby are supported.Leading ! changes the meaning of an include pattern to exclude.'
        default: "**/*.csproj"
        required: false
    github_token:
        description: "the github token to push changes"
        required: false
runs:
    using: "node12"
    main: "lib/main.js"
