export BRANCH="dev"
export GITHUB_RUN_ID="101"
export GITHUB_RUN_NUMBER="102"
export GITHUB_REPOSITORY="dotnet-bump-version"
export GITHUB_EVENT_PATH="dev-payload.json"
export GITHUB_EVENT_NAME="push"
export INPUT_NUMBER="123"